### PR TITLE
Make search result tabs accessible

### LINKED ISSUE #5964: [A11Y] Search results tabs are inaccessible
**Describe the bug**

The search result type tabs are not accessible using keyboard, and their role in relation to the result is unclear.

**To Reproduce**

1. Go to category display page
2. Enter a search keyword and confirm
3. On the search page, try to access the tabs using a keyboard
4. Observe that the tabs are not focusable

**Expected behavior**

Tabs are accessible using the keyboard, and their role is correctly announced as "tab" by the screen readers.

**Additional context**

- https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html
- https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html

### PR DESCRIPTION
**Pull request by foxbunny**
- Render tabs as buttons
- Add appropriate aria attributes and roles

Fixes #5964

### CODE REVIEW

File: indico/modules/search/client/js/components/SearchApp.jsx [hunk 1]
```diff
@@ -74,8 +74,27 @@ function SearchTypeMenuItem({index, active, title, total, loading, onClick}) {
...
+  let accessibleLabel = title;
+  if (loading) {
+    accessibleLabel = Translate.string('{title} (loading results)', {title});
+  } else if (!total) {
+    accessibleLabel = Translate.string('{title} (no results)', {title});
+  }
+
   return (
-    <Menu.Item index={index} active={active} onClick={onClick} disabled={loading || !total}>
+    <Menu.Item
```
Comment (ThiefMaster) [inline indico/modules/search/client/js/components/SearchApp.jsx:86]: Generally this all works fine, but I'm missing the `cursor: pointer;` now - having the default cursor feels weird, also because pretty much every other button, link, etc. has `cursor: pointer` so I guess this wasn't intentional.

Comment (foxbunny) [reply indico/modules/search/client/js/components/SearchApp.jsx:86]: Ah ok. I didn't pay attention to that because I figured it would've been taken care of at the library level. 😋 I'll fix it.

Comment (foxbunny) [reply indico/modules/search/client/js/components/SearchApp.jsx:86]: Added cursor styles for button and label to reset.

**Review by ThiefMaster — APPROVED** [review]
