### PR TITLE
Handle file upload errors in FileManager

### LINKED ISSUE #4203: FileManager: handle upload errors
Make it resilient to upload errors. The whole thing shouldn't blow up when an upload fails.

### PR DESCRIPTION
**Pull request by mic4ael**
closes #4203

### CODE REVIEW

File: indico/modules/events/editing/client/js/components/FileManager/util.js [hunk 1]
```diff
@@ -66,14 +66,20 @@ export function uploadFiles(action, fileTypeId, acceptedFiles, uploadURL, dispat
...
-      dispatch(
-        action(fileTypeId, fileId, tmpFileId, {
-          filename: uploadedFile.filename,
-          uuid: uploadedFile.uuid,
-          claimed: false,
-          fileType: fileTypeId,
-        })
-      );
+
+      if (uploadedFile === undefined) {
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileManager/util.js]: I'd rather make the function return `null` and check for that, instead of using an implicit `undefined` return value.

File: indico/modules/events/editing/client/js/components/FileManager/reducer.js [hunk 2]
```diff
@@ -119,6 +131,7 @@ export default combineReducers({
       case actions.MARK_DELETED:
       case actions.UNDELETE:
       case actions.REVERT:
+      case actions.UPLOAD_ERROR:
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileManager/reducer.js]: probably not needed since we use `isDirty` to trigger the `useEffect` that calls `onChange`, and an error does not change the value
