### PR TITLE
Fix wording in session block adjustment dialog

### LINKED ISSUE #3080: Session block adjustment: incorrect message wording
When ajusting a session block start/end time based on the session block contents, the message incorrectly says that the *session* start/end time will be adjusted instead of the *session block*. Also the expected session block name displayed is the session name (consistent with the wrong wording!) where it should be `session:block`. And there is also a missing space after the session (block) name.

This is confusing but probably easy to fix!

### PR DESCRIPTION
**Pull request by mvidalgarcia**
Fixes #3080

### CODE REVIEW

File: indico/htdocs/js/indico/modules/timetable/timetable/Management.js [hunk 1]
```diff
@@ -682,19 +682,19 @@ type("RescheduleDialog", ["ExclusivePopupWithButtons"], {
 type("FitInnerTimetableDialog", ["ConfirmPopup"], {
 
     /**
-     * Returns the title of the timetable/session/entry
+     * Returns the title of the session block
      */
-    __getSessionTitle: function(){
-        return '"' + this.tt.contextInfo.title + '"';
+    __generateSessionBlockTitle: function(slotData) {
+        return '"' + slotData.title + (slotData.slotTitle ? ": " + slotData.slotTitle : '') + '"';
```
Comment (ThiefMaster) [inline indico/htdocs/js/indico/modules/timetable/timetable/Management.js]: I would use single quotes here: `": "` to use only one style of quoting within the same statement/line.

File: indico/htdocs/js/indico/modules/timetable/timetable/Management.js [hunk 2]
```diff
@@ -682,19 +682,19 @@ type("RescheduleDialog", ["ExclusivePopupWithButtons"], {
 type("FitInnerTimetableDialog", ["ConfirmPopup"], {
 
     /**
-     * Returns the title of the timetable/session/entry
+     * Returns the title of the session block
      */
-    __getSessionTitle: function(){
-        return '"' + this.tt.contextInfo.title + '"';
+    __generateSessionBlockTitle: function(slotData) {
```
Comment (ThiefMaster) [inline indico/htdocs/js/indico/modules/timetable/timetable/Management.js]: i'm curious, why pass it as an argument instead of accessing it via `this.tt.contextInfo` here?

Comment (mvidalgarcia) [reply indico/htdocs/js/indico/modules/timetable/timetable/Management.js]: Not really a reason, I've just based it on a similar function but your way is actually cleaner.
