### PR TITLE
Fix Layout Issue in Filetype Manager

### LINKED ISSUE #4258: Fix layout issues in the `FileTypeManager`
Screenshot from 2020-01-24 12-50-13

### PR DESCRIPTION
**Pull request by ParthS007**
closes #4258 

**Updated Screenshot** 

Screenshot from 2020-01-28 15-31-51

### CODE REVIEW

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 1]
```diff
@@ -91,18 +92,20 @@ export default function FileTypeManager({eventId}) {
 
   const {operation, fileType: currentFileType} = state;
   return (
-    <div styleName="file-types-container">
+    <Segment className="ui basic" styleName="file-types-container">
```
Comment (mic4ael) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: `<Segment basic...`

**Comment by mic4ael** [comment]
I still don't think it is the best solution for the problem. This is what I managed to accomplish with only `TooltipIfTruncated` and a couple of CSS changes

image

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 2]
```diff
@@ -41,6 +42,18 @@ function fileTypesReducer(state, action) {
   }
 }
 
+function statusIcon(fileParam, iconName, text) {
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: It's a component so it should be named `StatusIcon`, and used as `<StatusIcon ... />` below instead of `{statusIcon(...)}`

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 3]
```diff
@@ -41,6 +42,18 @@ function fileTypesReducer(state, action) {
...
+  return (
+    <Icon
+      styleName={fileParam ? '' : 'disabled'}
+      size="small"
+      color={fileParam ? 'blue' : 'grey'}
+      name={iconName}
+      title={fileParam ? Translate.string(text) : ''}
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: Don't pass dynamic values to `Translate.string()`; this doesn't work since there's no way those values can be extracted for translation. Pass `Translate.string('...')` when using the StatusIcon component instead.

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 4]
```diff
@@ -41,6 +42,17 @@ function fileTypesReducer(state, action) {
   }
 }
 
+function StatusIcon({fileParam, iconName, text}) {
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: `active` would be a clearer name instead of `fileParam`

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 5]
```diff
@@ -208,3 +212,14 @@ export default function FileTypeManager({eventId}) {
 FileTypeManager.propTypes = {
   eventId: PropTypes.number.isRequired,
 };
+
+StatusIcon.propTypes = {
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: move this up to the component

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 6]
```diff
@@ -208,3 +212,14 @@ export default function FileTypeManager({eventId}) {
...
+  fileParam: PropTypes.bool.isRequired,
+  iconName: PropTypes.string,
+  text: PropTypes.string,
+};
+
+StatusIcon.defaultProps = {
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: you can make all props required and get rid of this

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 7]
```diff
@@ -99,65 +111,57 @@ export default function FileTypeManager({eventId}) {
...
+            }
+          />
+          <Icon
+            style={{cursor: 'pointer'}}
+            color="blue"
+            name="pencil"
+            corner="top right"
+            onClick={() => dispatch({type: 'EDIT_FILE_TYPE', fileType})}
+          />
+          <div styleName="filetype-head">
```
Comment (ThiefMaster) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: `filetype-header`

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx [hunk 8]
```diff
@@ -41,6 +42,17 @@ function fileTypesReducer(state, action) {
   }
 }
 
+function StatusIcon({fileParam, iconName, text}) {
+  return (
+    <Icon
+      size="small"
+      color={fileParam ? 'blue' : 'grey'}
+      name={iconName}
+      title={fileParam ? text : ''}
```
Comment (mic4ael) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: You can just use `text` (defaultProp for `text` is null which is valid here)

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx (hunk 4 above)
Comment (mic4ael) [inline indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: `icon` instead of `iconName`

File: indico/modules/events/editing/client/js/components/FileTypeManager.jsx (hunk 8 above)
Comment (ThiefMaster) [reply indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: There shouldn't be a default (as the prop is always specified); and `title={false}` would be very odd (and likely a proptypes violation)

Comment (mic4ael) [reply indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: I meant that `title` has default `null` which works fine in this case

Comment (mic4ael) [reply indico/modules/events/editing/client/js/components/FileTypeManager.jsx]: ahh, I see now.. nvm my comment
