### PR TITLE
Timeline fixes

### LINKED ISSUE #3777: Fix several timeline issues
1. Nonbookable periods/hours show up in the disabled days in weekly/monthly view

image

2. New booking appears below the current booking in booking edit when:
- we shorten the time of the booking
- we change booking from weekly to biweekly (in case of booking that didn't start yet) (screenshot below)
image

3. Element's border is cut out on the right side of the timeline

image

### PR DESCRIPTION
**Pull request by meluru**
Closes #3777

### CODE REVIEW

File: indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx [hunk 1]
```diff
@@ -89,7 +89,7 @@ export default class ElasticTimeline extends React.Component {
                 preConflicts: preConflicts[dt] || [],
                 blockings: blockings[dt] || [],
                 nonbookablePeriods: nonbookablePeriods[dt] || [],
-                unbookableHours: unbookableHours || [],
+                unbookableHours: dateRange.length !== 0 && !_.includes(dateRange, dt) ? [] : unbookableHours || [],
```
Comment (ThiefMaster) [inline indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx]: please add some parentheses, `a && b ? c : d || e` isn't really clear IMO

File: indico/modules/rb_new/client/js/common/timeline/TimelineLegend.module.scss [hunk 2]
```diff
@@ -70,6 +70,7 @@
             &.pre-booking {
                 @include stripes($pre-booking-stripe-colors...);
                 background-size: 35px 35px;
+                color: #c4930d;
```
Comment (ThiefMaster) [inline indico/modules/rb_new/client/js/common/timeline/TimelineLegend.module.scss]: shouldn't this come from the palette?

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx [hunk 3]
```diff
@@ -73,38 +73,56 @@ export default class MonthlyTimelineContent extends WeeklyTimelineContent {
...
         const nDays = this.dates.length;
         const daySize = (100 / nDays);
-
         const {dateRange} = this.props;
+
         const emptyDays = this.dates
             .filter(day => dateRange.length !== 0 && !dateRange.includes(day))
             .map(day => this.dates.findIndex((el) => el === day));
 
+        const weekendDays = this.dates
```
Comment (mvidalgarcia) [inline indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: I noticed you have this same operation in `renderHeader()`, perhaps could this be a separate function? It even could be a util function (`date.js`).

Apart from that, I think the weekend days aren't being properly calculated. For instance for the March you're highlighting Sunday and Monday.
image

File: indico/modules/rb_new/client/js/common/bookings/selectors.js [hunk 4]
```diff
@@ -27,8 +27,8 @@ const getRawDetails = (state, {bookingId}) => state.bookings.details[bookingId];
 
 
 function applyPermissionsToOccurrences(occurrences, override) {
-    return _.fromPairs(Object.entries(occurrences).map(([key, data]) => {
-        data = _.fromPairs(Object.entries(data).map(([day, dayData]) => {
+    return _.update(occurrences, 'bookings', (data) => {
```
Comment (ThiefMaster) [inline indico/modules/rb_new/client/js/common/bookings/selectors.js]: this mutates occurrences :/

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx [hunk 5]
```diff
@@ -35,6 +35,12 @@ export default class MonthlyTimelineContent extends WeeklyTimelineContent {
         return [];
     }
 
+    getWeekendDays = () => (
```
Comment (mvidalgarcia) [inline indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: What about `get weekendDays() {...}`? Then you can use directly `this.weekendDays`.

Comment (ThiefMaster) [reply indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: I'd use bracket style with return for this method. Using `=> ( ... )` over multiple lines without something that's obviously a return value (especially JSX) in the body isn't immediately clear without a closer look at the brackets. While looking at this PR I first thought there's a missing `return` statement

File: indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss [hunk 6]
```diff
@@ -156,3 +153,19 @@ $split-row-height: $row-height/2;
     overflow-x: hidden;
     overflow-y: auto;
 }
+
+
+.daily-timeline {
+    margin-right: 2em;
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss]: Why do you need it here? This margin makes the scrollbar e.g. in the `UnavailableRoomsModal` look a bit out of place.

File: indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss [hunk 7]
```diff
@@ -156,3 +153,19 @@ $split-row-height: $row-height/2;
...
+    display: flex;
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss]: Why do you need those flex-related properties here?

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx [hunk 8]
```diff
@@ -73,38 +81,49 @@ export default class MonthlyTimelineContent extends WeeklyTimelineContent {
     renderDividers() {
         const nDays = this.dates.length;
         const daySize = (100 / nDays);
-
         const {dateRange} = this.props;
+        const weekendDays = this.getWeekendDays();
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: This causes an error. IT should be `this.weekendDays`.

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx [hunk 9]
```diff
@@ -73,38 +81,49 @@ export default class MonthlyTimelineContent extends WeeklyTimelineContent {
...
+                         key={`day-divider-${n}`} />
+                );
+            })
         );
     }
 
     renderHeader() {
         const {longLabel, selectable} = this.props;
         const labelWidth = longLabel ? 200 : 150;
+        const weekendDays = this.getWeekendDays();
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: Error, there is no such method. `this.weekendDays`.

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx (hunk 8 above)
Comment (mvidalgarcia) [reply indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: Indeed [(getter docs)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get)

Comment (meluru) [reply indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: true, just forgot to change it here.

File: indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss (hunk 6 above)
Comment (meluru) [reply indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss]: Good point, it's not useful anymore

File: indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx [hunk 10]
```diff
@@ -89,7 +89,7 @@ export default class ElasticTimeline extends React.Component {
                 preConflicts: preConflicts[dt] || [],
                 blockings: blockings[dt] || [],
                 nonbookablePeriods: nonbookablePeriods[dt] || [],
-                unbookableHours: unbookableHours || [],
+                unbookableHours: (dateRange.length !== 0 && !_.includes(dateRange, dt)) ? [] : (unbookableHours || []),
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx]: You can use `Array.prototype.includes` instead of using `_.includes`

File: indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx [hunk 11]
```diff
@@ -73,38 +81,47 @@ export default class MonthlyTimelineContent extends WeeklyTimelineContent {
...
                     <div styleName="style.timeline-header-labels">
-                        {_.map(this.dates, (dt, n) => (
-                            <div styleName="style.timeline-header-label"
-                                 key={`timeline-header-${n}`}>
-                                <span styleName="style.timeline-label-text">
-                                    {toMoment(dt, 'YYYY-MM-DD').format('D')}
-                                </span>
-                            </div>
-                        ))}
+                        {_.map(this.dates, (dt, n) => {
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/MonthlyTimelineContent.jsx]: I am curious why we use `_.map` when we could use `Array.prototype.map` instead.

File: indico/modules/rb_new/client/js/common/timeline/TimelineItem.jsx [hunk 12]
```diff
@@ -148,7 +148,7 @@ class TimelineItem extends React.Component {
         const {startHour, endHour, onClickCandidate, onClickReservation, room, dayBased} = this.props;
         if (type === 'blocking') {
             segmentStartDt = moment(startHour, 'HH:mm');
-            segmentEndDt = moment(endHour, 'HH:mm');
+            segmentEndDt = (endHour === 24 ? moment('23:59', 'HH:mm') : moment(endHour, 'HH:mm'));
```
Comment (mic4ael) [inline indico/modules/rb_new/client/js/common/timeline/TimelineItem.jsx]: This is a pretty weird fix and anyway it is not needed as far as I can tell. The issue described in the task

> Element's border is cut out on the right side of the timeline

is solved by two places that you have already fixed in lines 129 and 239.

Comment (meluru) [reply indico/modules/rb_new/client/js/common/timeline/TimelineItem.jsx]: The issue with element border is solved in line 239.
This is a different problem I discovered on the way: blockings don't render properly if timeline `maxHour` is set to 24, because `segmentEndDt.hours()` will resolve to 0, so `segmentWidth` won't be correct

Comment (meluru) [reply indico/modules/rb_new/client/js/common/timeline/TimelineItem.jsx]: Line 129 fixes rendering occurrences that start at timeline maxHour, because we should treat them as out of bounds ones and we didn't

Comment (mic4ael) [reply indico/modules/rb_new/client/js/common/timeline/TimelineItem.jsx]: Ahh, I see now.

File: indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx (hunk 10 above)
Comment (ThiefMaster) [reply indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx]: `dateRange.includes(dt)` to be exact ;)

Comment (mic4ael) [reply indico/modules/rb_new/client/js/common/timeline/ElasticTimeline.jsx]: Yeah, yeah. That is what I meant :P

File: indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss [hunk 13]
```diff
@@ -156,10 +156,6 @@ $split-row-height: $row-height/2;
 
 
 .daily-timeline {
-    margin-right: 2em;
-    display: flex;
-    flex-direction: column;
-    flex: 1;
```
Comment (mvidalgarcia) [inline indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss]: Removing `flex` and `flex-direction` is breaking the edit booking timeline.
image

Comment (mic4ael) [reply indico/modules/rb_new/client/js/common/timeline/TimelineContent.module.scss]: Good catch.
