### PR TITLE
Fix participant roles table

### LINKED ISSUE #3511: Table layout looks broken after editing person data in "participant roles"
image

This happens only if at least one participant is registered (so the registration indicator icon shows up)

### PR DESCRIPTION
**Pull request by panagiotappl**
Table layout does not break after editing a person and there is at least one
registration icon showing

closes #3511

### CODE REVIEW

File: indico/htdocs/js/indico/modules/events/management.js [hunk 1]
```diff
@@ -110,6 +110,20 @@
         $('.js-reset-role-filter').toggleClass('disabled', isInitialState);
     }
 
+    function initTooltip() {
```
Comment (ThiefMaster) [inline indico/htdocs/js/indico/modules/events/management.js]: I would move this inside `setupEventPersonsList` since it's related to that (the whole management.js is a bit ugly/big, but not worth splitting/refactoring it now)

File: indico/htdocs/js/indico/modules/events/management.js [hunk 2]
```diff
@@ -248,6 +252,12 @@
             $checkbox.prop('checked', !$checkbox.prop('checked')).trigger('change');
             toggleResetBtn();
         });
+
+        var $eventParticipantsList = $('#event-participants-list');
```
Comment (ThiefMaster) [inline indico/htdocs/js/indico/modules/events/management.js]: since you use it only once, no need to assign it first. btw, let's use `const` in new code, even when adding it in an old file

File: indico/htdocs/js/indico/modules/events/management.js [hunk 3]
```diff
@@ -248,6 +252,12 @@
...
+
+        $eventParticipantsList.on('indico:htmlUpdated', function () {
```
Comment (ThiefMaster) [inline indico/htdocs/js/indico/modules/events/management.js]: This could be simplified like this (we don't put a space between `function` and `()` btw):

    $('#event-participants-list').on('indico:htmlUpdated', initTooltip);
